sudo: required
language: generic
services:
  - docker
before_install:
  - imagename="synker/k8s_enable_vcp:latest"
  - docker build -t $imagename .
  - docker run -idt $imagename
  - docker ps -a

deploy:
  provider: script
  skip_cleanup: true
  script: bash docker_push.sh
  on:
    branch: master