sudo: required
language: generic
services:
  - docker
before_install:
  - imagename="synker/k8s_enable_vcp"
  - docker build -t $imagename:latest .
  - docker build -t $imagename:$TRAVIS_BUILD_NUMBER .
  - docker run -idt $imagename:$TRAVIS_BUILD_NUMBER
  - docker ps -a

deploy:
  provider: script
  skip_cleanup: true
  script: bash docker_push.sh $imagename:$TRAVIS_BUILD_NUMBER && bash docker_push.sh $imagename:latest 
  on:
    branch: master