apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: vcp-daementset
  labels:
    name: vcp-daementset
  namespace: vmware
spec:
  template:
    metadata:
      name: vcp-pod
      labels:
        name: vcp-pod
    spec:
      serviceAccountName: vcpsa
      containers:
      - name: vcp-container
        image: cnastorage/enablevcp:v1
        env:
        - name: POD_ROLE
          value: "DAEMON"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: rootpath
          mountPath: /host
          readOnly: false
        - name: secret-volume
          mountPath: /secret-volume
          readOnly: true
      hostNetwork: true
      volumes:
        - name: rootpath
          hostPath:
            path: /
        - name: secret-volume
          secret:
            secretName: vsphere-cloud-provider-secret